# Parts based on https://github.com/godot-gdunit-labs/gdUnit4-action/blob/master/.gdunit4_action/godot-install/action.yml
# Rewritten to be cross-platform.

name: install-godot
description: 'Installs Godot'

inputs:
  godot-version:
    description: 'The Godot version (e.g. 4.7.2)'
    type: string
    required: true
  godot-release-type:
    description: "The type of the release (e.g. 'stable')"
    type: string
    required: true
    default: 'stable'
  install-path:
    description: 'Where the Godot binary is installed (e.g. at godotbinary directory in your godot.workspace path)'
    type: string
    required: true
    default: '${{ github.workspace }}/godotbinary'
  platform:
    description: "The Godot download file ending (linux.x86_64, macos.univeral, win64.exe)"
    type: string
    required: true
    default: 'linux.x86_64'

runs:
  using: composite
  steps:
    - name: 'Download Godot ${{ inputs.godot-version }}-${{ inputs.godot-release-type }}'
      # TODO: cache step.
      shell: bash
      run: |

        echo "Downloading Godot ${{ inputs.godot-version}} ${{ inputs.godot-release-type}} for ${{ inputs.platform }}"

        # Make the directory to install Godot to.
        mkdir -p ${{ inputs.install-path }}
        chmod 770 ${{ inputs.install-path }}

        # Make the config directory for Godot. TODO: Test if necessary.
        # GODOT_CONFIG="$HOME/.config/godot"
        # if [ ! -d "$GODOT_CONFIG" ]; then
          # mkdir -p "GODOT_CONFIG"
          # chmod 770 "$GODOT_CONFIG"
        # fi

        GODOT_DL_FILENAME="Godot_v${{ inputs.godot-version }}-${{ inputs.godot-release-type }}_${{ inputs.platform }}.zip"
        GODOT_DL_URL="https://github.com/godotengine/godot-builds/releases/download/$GODOT_DL_FILENAME"

        echo "Current at $(pwd)"
        cd ${{ inputs.install-path }}
        echo "Current at $(pwd)"
        echo "Pretend - Download $GODOT_DL_FILENAME from $GODOT_DL_URL"
        # curl --remote-name "$GODOT_DL_URL"
        cd -
        echo "Current at $(pwd)"
        unzip --version


