# Parts based on https://github.com/godot-gdunit-labs/gdUnit4-action/blob/master/.gdunit4_action/godot-install/action.yml
# Rewritten to be cross-platform.

name: install-godot
description: 'Installs Godot'

inputs:
  godot-version:
    description: 'The Godot version (e.g. 4.7.2)'
    type: string
    required: true
  godot-release-type:
    description: "The type of the release (e.g. 'stable')"
    type: string
    required: true
    default: 'stable'
  install-path:
    description: 'Where the Godot binary is installed (e.g. at godotbinary directory in your godot.workspace path)'
    type: string
    required: true
    default: '${{ github.workspace }}/godotbinary'
  platform:
    description: "The Godot download file ending (linux.x86_64, macos.univeral, win64.exe)"
    type: string
    required: true
    default: 'linux.x86_64'

runs:
  using: composite
  steps:
    - name: 'Download Godot ${{ inputs.godot-version }}-${{ inputs.godot-release-type }}'
      # TODO: cache step.
      shell: bash
      run: |

        echo "Downloading Godot ${{ inputs.godot-version}} ${{ inputs.godot-release-type}} for ${{ inputs.platform }}"

        # Make the directory to install Godot to.
        mkdir -p ${{ inputs.install-path }}
        chmod 770 ${{ inputs.install-path }}

        # Make the config directory for Godot. TODO: Test if necessary.
        # GODOT_CONFIG="$HOME/.config/godot"
        # if [ ! -d "$GODOT_CONFIG" ]; then
          # mkdir -p "GODOT_CONFIG"
          # chmod 770 "$GODOT_CONFIG"
        # fi

        GODOT_SHORTVERSION=${{ inputs.godot-version }}-${{ inputs.godot-release-type }}
        GODOT_FILENAME="Godot_v${GODOT_SHORTVERSION}_${{ inputs.platform }}"
        GODOT_DL_ZIPNAME="$GODOT_FILENAME.zip"
        GODOT_EXECUTABLE="${{ inputs.install-path }}/$GODOT_FILENAME"
        GODOT_RUN="${{ inputs.install-path }}/godot"
        if [[ "$GODOT_EXECUTABLE" == *".exe" ]]; then
          GODOT_RUN="$GODOT_RUN.exe"
        fi
        GODOT_DL_URL="https://github.com/godotengine/godot/releases/download/$GODOT_SHORTVERSION/$GODOT_DL_ZIPNAME"
        cd ${{ inputs.install-path }}
        echo "Pretend - Download $GODOT_DL_ZIPNAME from $GODOT_DL_URL"
        wcurl "$GODOT_DL_URL"
        unzip "$GODOT_DL_ZIPNAME"
        cd -
        mv "$GODOT_EXECUTABLE" "$GODOT_RUN"
        $GODOT_FILENAME --version


