# IMPORTANT: Must set a base name for REPO_NAME in the repositories variables.
# Extracting the name from the repo is possible, but tricky to use in every spot
# and the library name might not be the same as the repo, so this is how it is.

name: CMake CI

on:
  push:
    # branches: [ "main" ]
    tags:
      - 'v*'

env:
  REPO_NAME: ghactiontests

permissions:
  contents: write
  packages: write

jobs:

  build:
    runs-on: ${{ matrix.os }}
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        build_type: [Release]
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
            c_compiler: x86_64-w64-mingw32-gcc
            cpp_compiler: x86_64-w64-mingw32-g++
            extension: dll
          - os: ubuntu-latest
            arch: x86_64
            platform: linux
            c_compiler: gcc
            cpp_compiler: g++
            extension: so
          - os: macos-latest
            arch: x86_64
            platform: macos
            c_compiler: clang
            cpp_compiler: clang++
            extension: dylib


    steps:
    - uses: actions/checkout@v7

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "input_file=lib${{ var.REPO_NAME }}.${{ matrix.extension }}" >> "$GITHUB_OUTPUT"
        echo "output_file=${{ var.REPO_NAME }}.${{ matrix.build_type }}.${{ matrix.arch }}.${{ matrix.extension }}" >> "$GITHUB_OUTPUT"

    - name: Install Latest CMake
      uses: ssrobins/install-cmake@v1

    - name: Install GCC 16
      if: matrix.os == 'ubuntu-latest'
      uses: egor-tensin/setup-gcc@v2
      with:
        version: 16
        platform: x64    

    - name: Install Latest MinGW
      if: matrix.os == 'windows-latest'
      uses: egor-tensin/setup-mingw@v3
      with:
        platform: x64

    - name: Verify MinGW Installation
      if: matrix.os == 'windows-latest'
      run: |
        x86_64-w64-mingw32-gcc --version
        x86_64-w64-mingw32-g++ --version

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
        -G Ninja

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --verbose

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Rename Output
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: pwsh
      run: Move-Item -Path ${{ steps.strings.outputs.input_file }} -Destination ${{ steps.strings.outputs.output_file }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.strings.outputs.output_file }}
        path: ${{ steps.strings.outputs.build-output-dir }}/${{ steps.strings.outputs.output_file }}
  
    # Only doing for one OS, save time kinda.?
    - name: Generate a changelog
      uses: orhun/git-cliff-action@v4
      id: git-cliff
      with:
        config: cliff.toml
        args: --latest --strip=header
      env:
        OUTPUT: CHANGES.md

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download All Artifacts
      uses: actions/download-artifact@v8
      with:
        path: addons/${{ vars.REPO_NAME }}
        merge-multiple: true

    - name: Build Archives
      run: |
        zip -r ${{ vars.REPO_NAME }}-${{ github.ref_name }}.zip addons/
        tar -czvf ${{ vars.REPO_NAME }}-${{ github.ref_name }}.tar.gz addons
        sha256sum ${{ vars.REPO_NAME }}-*.tar.gz ${{ vars.REPO_NAME }}-*.zip > checksums.txt
        ls -alhR
    
    - name: Publish Release
      uses: softprops/action-gh-release@v3
      with:
        body: ${{ needs.build.outputs.release_body }}
        files: |
          ${{ vars.REPO_NAME }}-${{ github.ref_name }}.zip
          ${{ vars.REPO_NAME }}-${{ github.ref_name }}.tar.gz
          checksums.txt