# IMPORTANT: Must set a base name for REPO_NAME in the repositories variables.
# Extracting the name from the repo is possible, but tricky to use in every spot
# and the library name might not be the same as the repo, so this is how it is.

name: CMake CI

on:
  push:
    branches: [ "develop" ]

env:
  REPO_NAME: ghactiontests

jobs:

  build:
    runs-on: ${{ matrix.target.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        include:
          - target: { os: windows-latest, platform: windows, arch: x86_64 }
            c_compiler: x86_64-w64-mingw32-gcc
            cpp_compiler: x86_64-w64-mingw32-g++
            extension: dll
            generator: Ninja
            build_type: Debug
          - target: { os: ubuntu-latest, platform: linux, arch: x86_64 }
            c_compiler: gcc
            cpp_compiler: g++
            extension: so
            generator: Ninja
            build_type: Debug
          - target: {os: macos-latest, platform: macos, arch: x86_64 }
            mac_platform: MAC_CATALYST
            c_compiler: clang
            cpp_compiler: clang++
            extension: dylib
            generator: Xcode
            build_type: Debug
          - target: {os: macos-latest, platform: ios, arch: arm64 }
            mac_platform: OS64
            c_compiler: clang
            cpp_compiler: clang++
            extension: dylib
            generator: Xcode
            build_type: Debug


    steps:
    - uses: actions/checkout@v7

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install Latest CMake
      uses: ssrobins/install-cmake@v1

    - name: Install GCC 16
      if: matrix.target.os == 'ubuntu-latest'
      uses: egor-tensin/setup-gcc@v2
      with:
        version: 16
        platform: x64    

    - name: Install Latest MinGW
      if: matrix.target.os == 'windows-latest'
      uses: egor-tensin/setup-mingw@v3
      with:
        platform: x64

    - name: Verify MinGW Installation
      if: matrix.target.os == 'windows-latest'
      run: |
        x86_64-w64-mingw32-gcc --version
        x86_64-w64-mingw32-g++ --version

    - name: Configure CMake (Win/Lunix)
      if: matrix.target.os != 'macos-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
        -G ${{ matrix.generator }}

    - name: Configure CMake (Mac/iOS)
      if: matrix.target.os == 'macos-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=cmake/ios-cmake/ios.toolchain.cmake
        -DPLATFORM=${{ matrix.mac_platform }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
        -G ${{ matrix.generator }}


    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --verbose

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }}
