# Testing for teeny tiny CI bits.

name: Tinytest

on:
  push:
    branches: [ 'tinytest/**' ]

jobs:
  prepare:
    runs-on: ${{ matrix.os }}
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Detect OS
        uses: ./.github/actions/detect-os
        id: detect-os

      - name: Download Godot
        uses: ./.github/actions/download-godot
        with:
          godot-version: 4.7.2
          platform: ${{ steps.detect-os.outputs.godot-os }}